[package]
name = "database"
version.workspace = true
edition.workspace = true

[dependencies]
sqlx.workspace = true
serde.workspace = true

# Use another workspace member
shared-utils = { path = "../shared-utils" }
